// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuZTg_fbnzQ41WCXPgyLR9m6-YWHBxEL0',
    appId: '1:81572583127:web:139adc06b31bdf93e24292',
    messagingSenderId: '81572583127',
    projectId: 'elderlyconnect-9e23f',
    authDomain: 'elderlyconnect-9e23f.firebaseapp.com',
    storageBucket: 'elderlyconnect-9e23f.appspot.com',
    measurementId: 'G-Q6YDN86PH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGJ7cXQMcxLbT39uplXjmXEflsANmaQPo',
    appId: '1:81572583127:android:71876bd982d1a36ee24292',
    messagingSenderId: '81572583127',
    projectId: 'elderlyconnect-9e23f',
    storageBucket: 'elderlyconnect-9e23f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOe1dcDS_EvEetDZntxhhAXDURJlZ_rMc',
    appId: '1:81572583127:ios:50c93108903340ffe24292',
    messagingSenderId: '81572583127',
    projectId: 'elderlyconnect-9e23f',
    storageBucket: 'elderlyconnect-9e23f.appspot.com',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOe1dcDS_EvEetDZntxhhAXDURJlZ_rMc',
    appId: '1:81572583127:ios:50c93108903340ffe24292',
    messagingSenderId: '81572583127',
    projectId: 'elderlyconnect-9e23f',
    storageBucket: 'elderlyconnect-9e23f.appspot.com',
    iosBundleId: 'com.example.healthcare',
  );
}
